/** Synthetic source fixtures; no ERP account, credentials or writes. */
const common = {
  company: "DEMO · Atelier Nord",
  modified: "2026-09-13 09:42:18",
  owner: "demo@example.invalid",
};
export const OPERATIONAL_FIXTURES: Record<
  string,
  { data: Record<string, unknown>; _availableTools: string[] }
> = {
  project: {
    _availableTools: [],
    data: {
      ...common,
      doctype: "Project",
      name: "DEMO-PROJ-0042",
      project_name: "Modular assembly cell · Aster 04",
      status: "Open",
      percent_complete: 42,
      percent_complete_method: "Task Progress",
      actual_time: 118.5,
      priority: "High",
      project_type: "External",
      customer: "DEMO-CUSTOMER-008",
      expected_start_date: "2026-09-01",
      expected_end_date: "2026-10-16",
      actual_start_date: "2026-09-02",
      actual_end_date: null,
      estimated_costing: 28500,
      total_costing_amount: 9480,
      total_purchase_cost: 13640,
      total_consumed_material_cost: 0,
      notes:
        "Synthetic demonstration. Mechanical assembly, controls integration and commissioning of a modular production cell. Costs are fictional; the document does not supply a company currency.",
      users: [{
        user: "lead@example.invalid",
        full_name: "Camille Martin",
        view_attachments: 1,
      }, {
        user: "controls@example.invalid",
        full_name: "Lin Chen",
        view_attachments: 1,
      }],
    },
  },
  task: {
    _availableTools: [],
    data: {
      ...common,
      doctype: "Task",
      name: "DEMO-TASK-0142",
      subject: "Validate the assembly sequence",
      status: "Working",
      project: "DEMO-PROJ-0042",
      parent_task: "DEMO-TASK-0100",
      priority: "High",
      is_milestone: 0,
      progress: 62,
      expected_time: 24,
      actual_time: 14.5,
      exp_start_date: "2026-09-08",
      exp_end_date: "2026-09-16",
      act_start_date: "2026-09-09",
      act_end_date: null,
      total_costing_amount: 1160,
      total_billing_amount: 1740,
      description:
        "Synthetic demonstration. Check the supplied assembly sequence and document unresolved interfaces before commissioning.",
      depends_on: [{
        task: "DEMO-TASK-0128",
        subject: "Complete mechanical interfaces",
        project: "DEMO-PROJ-0042",
      }, {
        task: "DEMO-TASK-0134",
        subject: "Review controls I/O list",
        project: "DEMO-PROJ-0042",
      }],
    },
  },
  timesheet: {
    _availableTools: [],
    data: {
      ...common,
      doctype: "Timesheet",
      name: "DEMO-TS-0084",
      title: "Controls engineering · week 37",
      status: "Draft",
      docstatus: 0,
      employee: "DEMO-EMP-0008",
      employee_name: "Lin Chen",
      parent_project: "DEMO-PROJ-0042",
      start_date: "2026-09-08",
      end_date: "2026-09-10",
      total_hours: 14.5,
      total_billable_hours: 12,
      total_billed_hours: 0,
      currency: "EUR",
      total_costing_amount: 1160,
      total_billable_amount: 1740,
      total_billed_amount: 0,
      note: "Synthetic demonstration. All hours and costs are fictional.",
      time_logs: [{
        name: "demo-log-1",
        activity_type: "Controls engineering",
        project: "DEMO-PROJ-0042",
        task: "DEMO-TASK-0142",
        hours: 8,
        from_time: "2026-09-08 09:00:00",
        to_time: "2026-09-08 17:00:00",
        is_billable: 1,
        costing_amount: 640,
        billing_amount: 960,
      }, {
        name: "demo-log-2",
        activity_type: "Sequence review",
        project: "DEMO-PROJ-0042",
        task: "DEMO-TASK-0142",
        hours: 6.5,
        from_time: "2026-09-10 09:00:00",
        to_time: "2026-09-10 15:30:00",
        is_billable: 1,
        costing_amount: 520,
        billing_amount: 780,
      }],
    },
  },
  bom: {
    _availableTools: [],
    data: {
      ...common,
      doctype: "BOM",
      name: "DEMO-BOM-ASTER-001",
      item: "DEMO-ASTER-BASE",
      item_name: "Aster 04 · base assembly",
      docstatus: 1,
      quantity: 1,
      uom: "Nos",
      is_active: 1,
      is_default: 1,
      currency: "EUR",
      routing: "DEMO-ROUTE-ASSEMBLY",
      raw_material_cost: 685,
      operating_cost: 135,
      secondary_items_cost: 0,
      total_cost: 820,
      rm_cost_as_per: "Valuation Rate",
      description:
        "Synthetic demonstration. A fictional manufacturing bill of materials; amounts are explicit demo values.",
      items: [{
        name: "demo-bom-row-1",
        item_code: "DEMO-PLATE-420",
        item_name: "Machined base plate · 420 × 280 mm",
        qty: 1,
        uom: "Nos",
        rate: 420,
        amount: 420,
        source_warehouse: "DEMO-Raw Materials",
      }, {
        name: "demo-bom-row-2",
        item_code: "DEMO-RAIL-240",
        item_name: "Linear guide rail · 240 mm",
        qty: 2,
        uom: "Nos",
        rate: 110,
        amount: 220,
      }, {
        name: "demo-bom-row-3",
        item_code: "DEMO-FASTENER-M8",
        item_name: "M8 assembly fasteners",
        qty: 1,
        uom: "Set",
        rate: 45,
        amount: 45,
      }],
      operations: [{
        operation: "Mechanical assembly",
        workstation: "DEMO-BENCH-02",
        time_in_mins: 90,
        hour_rate: 60,
        operating_cost: 90,
        sequence_id: 10,
      }, {
        operation: "Dimensional inspection",
        workstation: "DEMO-METROLOGY-01",
        time_in_mins: 30,
        hour_rate: 90,
        operating_cost: 45,
        sequence_id: 20,
      }],
    },
  },
  "work-order": {
    _availableTools: [],
    data: {
      ...common,
      doctype: "Work Order",
      name: "DEMO-MFG-WO-0026",
      production_item: "DEMO-ASTER-BASE",
      item_name: "Aster 04 · production batch",
      status: "In Process",
      docstatus: 1,
      bom_no: "DEMO-BOM-ASTER-001",
      project: "DEMO-PROJ-0042",
      qty: 12,
      produced_qty: 4,
      material_transferred_for_manufacturing: 8,
      stock_uom: "Nos",
      fg_warehouse: "DEMO-Finished Goods",
      planned_start_date: "2026-09-10 08:00:00",
      planned_end_date: "2026-09-16 17:00:00",
      actual_start_date: "2026-09-10 08:24:00",
      actual_end_date: null,
      planned_operating_cost: 1620,
      actual_operating_cost: 586,
      additional_operating_cost: 0,
      total_operating_cost: 1620,
      description:
        "Synthetic demonstration. Quantities, durations and costs are fictional ERP-shaped values. No progress ratio or total is calculated by this viewer.",
      required_items: [{
        name: "demo-wo-row-1",
        item_code: "DEMO-PLATE-420",
        item_name: "Machined base plate",
        required_qty: 12,
        transferred_qty: 8,
        consumed_qty: 4,
        source_warehouse: "DEMO-Raw Materials",
        stock_uom: "Nos",
      }, {
        name: "demo-wo-row-2",
        item_code: "DEMO-RAIL-240",
        item_name: "Linear guide rail",
        required_qty: 24,
        transferred_qty: 16,
        consumed_qty: 8,
        stock_uom: "Nos",
      }],
      operations: [{
        operation: "Mechanical assembly",
        status: "Work in Progress",
        workstation: "DEMO-BENCH-02",
        time_in_mins: 1080,
        actual_operation_time: 406,
        completed_qty: 4,
        planned_operating_cost: 1080,
        actual_operating_cost: 406,
        sequence_id: 10,
      }, {
        operation: "Dimensional inspection",
        status: "Work in Progress",
        workstation: "DEMO-METROLOGY-01",
        time_in_mins: 360,
        actual_operation_time: 120,
        completed_qty: 4,
        planned_operating_cost: 540,
        actual_operating_cost: 180,
        sequence_id: 20,
      }],
    },
  },
  "job-card": {
    _availableTools: [],
    data: {
      ...common,
      doctype: "Job Card",
      name: "DEMO-JOB-0068",
      item_name: "Mechanical assembly · batch 26",
      status: "Work In Progress",
      docstatus: 0,
      work_order: "DEMO-MFG-WO-0026",
      bom_no: "DEMO-BOM-ASTER-001",
      operation: "Mechanical assembly",
      workstation: "DEMO-BENCH-02",
      production_item: "DEMO-ASTER-BASE",
      for_quantity: 12,
      total_completed_qty: 4,
      total_time_in_mins: 406,
      time_required: 1080,
      expected_start_date: "2026-09-10 08:00:00",
      expected_end_date: "2026-09-15 16:00:00",
      actual_start_date: "2026-09-10 08:24:00",
      actual_end_date: null,
      remarks:
        "Synthetic demonstration. This Job Card does not supply a quantity UOM. No unit is inferred from its item or Work Order.",
      time_logs: [{
        name: "demo-job-log-1",
        employee: "DEMO-EMP-0012",
        from_time: "2026-09-10 08:24:00",
        to_time: "2026-09-10 11:50:00",
        time_in_mins: 206,
        completed_qty: 2,
      }, {
        name: "demo-job-log-2",
        employee: "DEMO-EMP-0012",
        from_time: "2026-09-11 08:00:00",
        to_time: "2026-09-11 11:20:00",
        time_in_mins: 200,
        completed_qty: 2,
      }],
    },
  },
};
export function operationalFixture(search: string) {
  const key = new URLSearchParams(search).get("fixture") ?? "";
  return Object.hasOwn(OPERATIONAL_FIXTURES, key)
    ? OPERATIONAL_FIXTURES[key]
    : undefined;
}
